const ACTIONS = {
    SHOW_EDIT_MODAL: "SHOW_EDIT_MODAL",
    SHOW_DELETE_MODAL: "SHOW_DELETE_MODAL",
    SET_SEARCH_TXT: "SET_SEARCH_TXT",
    SEARCH_FOR_MOVIE: "SEARCH_FOR_MOVIE",
    SET_GENRE_FILTER: "SET_GENRE_FILTER",
    SET_ORDER_BY: "SET_ORDER_BY",
    LOAD_MOVIES: "LOAD_MOVIES"

}

export default ACTIONS;