const ACTIONS = {
    SHOW_EDIT_MODAL: "SHOW_EDIT_MODAL",
    SHOW_DELETE_MODAL: "SHOW_DELETE_MODAL",
    SET_SEARCH_TXT: "SET_SEARCH_TXT",
    SEARCH_FOR_MOVIE: "SEARCH_FOR_MOVIE",
}

export default ACTIONS;