const ACTIONS = {
    SHOW_EDIT_MODAL: "SHOW_EDIT_MODAL",
    SHOW_DELETE_MODAL: "SHOW_DELETE_MODAL",
    SHOW_ADD_MOVIE_MODAL: "SHOW_ADD_MOVIE_MODAL",
    SET_SEARCH_TXT: "SET_SEARCH_TXT",
    SEARCH_FOR_MOVIE: "SEARCH_FOR_MOVIE",
    SET_GENRE_FILTER: "SET_GENRE_FILTER",
    SET_ORDER_BY: "SET_ORDER_BY",
    LOAD_MOVIES: "LOAD_MOVIES",
    ADD_MOVIE: "ADD_MOVIE",
    EDIT_MOVIE: "EDIT_MOVIE",
    DELETE_MOVIE: "DELETE_MOVIE",
    ADD_MOVIE_FORM_CHANGED: "ADD_MOVIE_FORM_CHANGED"

}

export default ACTIONS;